# Generated by Django 5.1.4 on 2024-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_category_movie_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.category'),
        ),
    ]
